### ISSUE TITLE
error found when run this code

### ISSUE THREAD

**Issue by monika21089** [asaini/Apriori#4]
Traceback (most recent call last):
  File "<module1>", line 178, in <module>
  File "<module1>", line 77, in runApriori
  File "<module1>", line 62, in getItemSetTransactionList
TypeError: 'AsyncStream' object is not iterable

what should i do to correct this error

**Comment by asaini** [comment]
Hi @monika21089 

Have you tried using a file object instead of a AsyncStream object?

**Comment by asaini** [comment]
Closing, no response!
